export const CONTRACT_VERSIONS = {
  Queen: {
    name: 'QueenOutput',
    version: '1.2.0',
    promptVersion: '1.2.0',
    validatorVersion: '1.2.0',
    outputArtifactName: 'plan.md',
    format: 'markdown',
    requiredHeadings: [
      '### Project Name',
      '### Project Goal',
      '### MVP Scope',
      '### Technical Constraints',
      '### Risks',
    ],
  },
  Planner: {
    name: 'PlannerOutput',
    version: '1.2.0',
    promptVersion: '1.2.0',
    validatorVersion: '1.2.0',
    outputArtifactName: 'requirements.md',
    format: 'markdown',
    requiredHeadings: [
      '### Features',
      '### Functional Requirements',
      '### Acceptance Criteria',
    ],
  },
  Architect: {
    name: 'ArchitectureOutput',
    version: '1.2.0',
    promptVersion: '1.2.0',
    validatorVersion: '1.2.0',
    outputArtifactName: 'architecture.md',
    format: 'markdown',
    requiredHeadings: [
      '### Tech Stack',
      '### Project Folder Structure',
      '### Project Files',
      '### Modules',
      '### Conventions',
    ],
  },
  System: {
    name: 'SystemOutput',
    version: '1.2.0',
    promptVersion: '1.2.0',
    validatorVersion: '1.2.0',
    outputArtifactName: 'backend_spec.md',
    format: 'markdown',
  },
  Designer: {
    name: 'DesignerOutput',
    version: '1.2.0',
    promptVersion: '1.2.0',
    validatorVersion: '1.2.0',
    outputArtifactName: 'ui_spec.md',
    format: 'markdown',
    requiredHeadings: [
      '### Design System',
      '### Pages',
      '### Components',
      '### Global Feedback',
    ],
  },
  Blueprinter: {
    name: 'BlueprintOutput',
    version: '1.2.0',
    promptVersion: '1.2.0',
    validatorVersion: '1.2.0',
    outputArtifactName: 'blueprint.md',
    format: 'markdown',
    repeatedHeading: '### File:',
  },
  Coder: {
    name: 'CoderOutput',
    version: '1.2.0',
    promptVersion: '1.2.0',
    validatorVersion: '1.2.0',
    outputArtifactName: 'workspace.manifest.json',
    format: 'json',
  },
  Tester: {
    name: 'TesterOutput',
    version: '1.2.0',
    promptVersion: '1.2.0',
    validatorVersion: '1.2.0',
    outputArtifactName: 'test_report.md',
    format: 'markdown',
    requiredHeadings: [
      '### Result',
      '### Summary',
      '### Tests',
      '### Failures',
      '### Workspace Hash',
    ],
  },
  Debugger: {
    name: 'DebuggerOutput',
    version: '1.2.0',
    promptVersion: '1.2.0',
    validatorVersion: '1.2.0',
    outputArtifactName: 'debug_report.md',
    format: 'json',
    requiredHeadings: [
      '### Issues Addressed',
      '### Patches Applied',
      '### Verification',
    ],
  },
  Reviewer: {
    name: 'ReviewerOutput',
    version: '1.2.0',
    promptVersion: '1.2.0',
    validatorVersion: '1.2.0',
    outputArtifactName: 'review_report.md',
    format: 'json',
  },
  Security: {
    name: 'SecurityOutput',
    version: '1.2.0',
    promptVersion: '1.2.0',
    validatorVersion: '1.2.0',
    outputArtifactName: 'security_report.md',
    format: 'markdown',
    requiredHeadings: [
      '### Status',
      '### Vulnerabilities',
      '### Recommendations',
      '### Workspace Hash',
    ],
  },
} as const;

export type StageName = keyof typeof CONTRACT_VERSIONS;
